other-uses.md

This PR updates the Other Uses page, removing discontinued products, updating links, and adding links to products and projects that’ve sprung up since the page was originally written.
In the interest of fairness, I’ve included links to not only the libraries I work on but also its competitors. In the interest of simplicity, I’ve omitted many map libraries that are less sophisticated (lacking vector map support) or target less common environments (like Windows Phone). That said, there are certainly better ways of organizing this information. [This wiki page](http://wiki.openstreetmap.org/wiki/Frameworks), though complete, must be overwhelming to this site’s readers, but maybe we can strike a balance somehow.

Update Other Uses page

---

serving-tiles/manually-building-a-tile-server-16-04-2-lts.md

Other working pages have the trailing slash e.g https://raw.githubusercontent.com/switch2osm/switch2osm.github.io/master/serving-tiles/building-a-tile-server-from-packages.md (amongst the others)
It's a clue from my viewpoint to solve the issue.
From my viewpoint, merge & let's wait and see :)

Missing trailing slash to solve #39

---

_config.yml
serving-tiles/manually-building-a-tile-server-18-04-lts.md

moved a caveat recently added from the 16.04 wordpress page over.

Added 18.04 page and 

---

serving-tiles/manually-building-a-tile-server-18-04-lts.md

The changes are to update the displayed carto version and to use a sample html file (from Paul Norman) instead of switcheroo.

Updated the github version to match wordpress.

---

.travis.yml

Change Ruby version to support bundler and fix CI failing.
Bundler only support Ruby 2.3+ e.g https://docs.travis-ci.com/user/languages/ruby/#bundler-20

Update in .travis.yml ruby version to 2.3 due to bundler

---

_config.yml
_sass/_page.scss

With merge of #60, the site has been broken due to hosting difference e.g https://klokantech.github.io/switch2osm/ (so with a subpath) vs http://switch2osm.github.io/ (no subpath)
This PR fixes the issue.

Fix due to deploy issue with new design

---

Gemfile.lock
_config.yml

Workaround:
https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html
And exclude some files from build.

Bundler fix

---

_config.yml

Exclude vendor folder to workaround https://github.com/jekyll/jekyll/issues/5267

Exclude vendor folder

---

_config_osm.yml

Add a config file to use for overriding the `site.url`

Add override config for when building for switch2osm.org

---

the-basics/index.md

Because they were all in one "paragraph", the list no longer worked as intended.

Fixed layout

---

serving-tiles/index.md

Link to protomaps.com/extracts as another extract source.
http://metro.teczno.com/ has been a dead link for a few years now. I'm running a free minutely-updated on-demand extracts service now that I can provide as an alternative. 
With regards to the README guidelines:
> Does not require specific external services, aside from OpenStreetMap itself
> 
> We do not promote anything which can result in lock-in to a specific vendor, so guides need to be usable without relying on a third party. It's okay to use something as an example (e.g. tile.osm.org) where there are plenty of alternatives, but not if there are few alternatives or the service being used cannot be reproduced.
I think that this service should be okay, given that there are plenty of alternatives and it is self-hostable (includes …

replace dead link for metro extracts

---

_config.yml

Not a fan of Americanised capitalisation personally, but at least let's make this consistent.

Fix inconsistent capitalisation in menu

---

other-uses.md
providers.md

OpenCage started as consultancy but now does geocoding SaaS exclusively. 
I'm not sure if Mapbox still counts as consultancy, I'd count https://developmentseed.org/ though.

remove OpenCage from development services and consulting list

---

providers.md

I was kinda surprised to *not* see @gravitystorm's thunderforest (of opencyclemap hosting fame) in the list of providers for the revamped switch2osm... so there.
There's a free tier (detailed in https://www.thunderforest.com/pricing/), so I'm adding the link in the "allows free usage" section.

Add thunderforest.com to tile providers

---

other-uses.md

MapQuest is not really available anymore (at least not for  free). For Nominatim, change primary URL to nominatim.org.

Update link for Nominatim and remove MapQuest

---

_layouts/docs.html
serving-tiles/index.md
serving-tiles/using-a-docker-container.md

"with packages" does (likely) still work, but is less and less
relevant as Ubuntu 14.04 isn't mainstream any more.

Swap around "manually 18.04" and "with packages".

---

_layouts/docs.html

Added https://switch2osm.org/serving-tiles/using-a-docker-container/ page into the layout.

Added link to docker page into docs.html.

---

serving-tiles/index.md

Should resolve https://github.com/switch2osm/switch2osm.github.io/issues/98 once merged.

Fixing typo in one of links to old packaged instructions.

---

the-basics/index.md

Link direct to the policy at operations.osmfoundation.org, not the old wiki location (which just links onward to there)

Fix tile usage policy link

---

providers.md

Could you please kindly mention us as a tile provider? We offer free vector and raster tiles, without any restrictions on commercial use. 
And, thank you for the switch2osm! Great resource. Hope to give more valuable contributions to it one day.

Add Geoapify as map tile and service provider

---

providers.md

Ito World are no longer (and haven't for several years) providing consulting services for organisations interested in OSM data. We still use OSM data internally and for a few services, however don't want to advertise and attract clients for this as it's not a core part of our business. Linked to #53

Remove Ito World as a provider

---

other-uses.md

* Link to GitHub repository of GraphHopper, not the company because not all features advertised on their company website are open source.
* Add GraphHopper as routing API. They offer a small free plan as the other two do. I presume that's one of the selection criteria, isn't it?
* Add Valhalla
* Drop Gosmore because its last release is about 8 years ago.
* Drop KothicJS because its development ceased a few years ago.

Clean up "other uses" page

---

serving-tiles/using-a-docker-container.md

Docker container now uses postgres 12.
I've also linked to the version of the docker container (actually 1.3.10) to avoid this being an issue in the future.

Updated docker instructions to match latest docker container.

---

_layouts/docs.html
serving-tiles/index.md
serving-tiles/manually-building-a-tile-server-20-04-lts.md

There are no major changes - just incremented versions, such as python3 instead of python.
I've quickly tested this locally with "OSM Standard" tiles in Burma (to check fonts).
I haven't done extensive lua testing yet, nor done a side-by-side comparison of generated tiles, but it makes sense to get a 20.04 version of this guide out there so that people can at least easily get to the stage of seeing what's changed (if anything) in the software versions used here compared to the previous one.

Added 20.04 instructions, and also reorganised the index page.

---

serving-tiles/manually-building-a-tile-server-16-04-2-lts.md
serving-tiles/manually-building-a-tile-server-18-04-lts.md
serving-tiles/manually-building-a-tile-server-20-04-lts.md

Apply changes requested in https://github.com/switch2osm/switch2osm.github.io/issues/124 
18.04 and 20.04 changed after testing
16.04 not changed, tested or removed (it is still supported and is deliberately the "last in the list"); but caveats added.

Apply changes requested in https://github.com/switch2osm/switch2osm.github.io/issues/124 

---

README.md
serving-tiles/manually-building-a-tile-server-20-04-lts.md

More modern, user friendly, and 4 characters less to type.

Use apt instead of apt-get for installing packages

---

serving-tiles/manually-building-a-tile-server-debian-11.md

Following the work done at https://github.com/openstreetmap/mod_tile/issues/217 , here's a switch2osm page for Debian 11.  Initially it is just standalone, but once people have had a chance to test it I'll link it to the menus.

Added page for Debian 11 (initially standalone; not linked to menus).

---

serving-tiles/manually-building-a-tile-server-16-04-2-lts.md
serving-tiles/manually-building-a-tile-server-18-04-lts.md
serving-tiles/manually-building-a-tile-server-20-04-lts.md

Minor typo in each file; spotted while doing the Debian page.
Currently the upstream problem described at https://github.com/gravitystorm/openstreetmap-carto/issues/4249 applies to each of these pages, but hopefully that will be fixed soon at Natural Earth, and the workaround is documented at OSM Carto.

Fixed typo "bondaries" (boundaries) in each of these files.

---

serving-tiles/manually-building-a-tile-server-debian-11.md

The bug is fixed so it is no longer needed.

Removed CDN workaround from the Debian instructions.

---

serving-tiles/updating-as-people-edit.md

See https://help.openstreetmap.org/questions/78817/keep-in-sync-local-database-with-osm-latest-changes-to-region
Also, I saw this in OSM data at around "seq-nr 4297047" from last year, with the current map style.

Add another "potential problem" based on if osm2pgsql fails

---

serving-tiles/manually-building-a-tile-server-debian-11.md

As noted at https://github.com/switch2osm/switch2osm.github.io/issues/150 , new indexes are now required rather than merely recommended.
I also noticed that Debian have updated Mapnik to 3.1, which requires an edit to a previous renderd.conf.  The Debian update process actually tells you that a new file is available and tells you that you edited the old one, and offers to show you a diff, so they literally can't do any more here.

Issue 150 fix and mapnik version caveat

---

_layouts/docs.html
serving-tiles/manually-building-a-tile-server-ubuntu-21.md

Added Ubuntu 21 page to the index.
Also a couple of other minor changes to the Ubuntu 21 page - replace some data that was copied from Debian with data referencing "now" rather than "2020".

Added Ubuntu 21 page to the index.

---

providers.md

Hi there.
SmartMaps (formerly known as YellowMaps) was established more than ten years ago and is developed by YellowMap AG which is a Bronze Corporate Member of the OSM foundation.
In addition to a free usage via SmartMaps Free, we also provide assistance and support when switiching to OSM from other map platforms.
It would be great to be added to these lists.
Thank you :)

added SmartMaps to providers list

---

serving-tiles/updating-as-people-edit.md

"src/openstreetmap-carto/openstreetmap-carto.style" has changed, and "addr:interpolation" is no longer stored for nodes.  This makes logical sense and is a bugfix in openstreetmap-carto, but is different to osm2pgsql's default.  This means that "OSM2PGSQL_OPTIONS" needs to reference the .style file that was used to create the database in the first place (arguably, it always should have done this).
The actual location of the .style file depends on the account that the user used to fetch it, and on Debian it'll always be different to the account that renderd runs under.
https://help.openstreetmap.org/questions/78817/keep-in-sync-local-database-with-osm-latest-changes-to-region is an example of this problem elsewhere.

Add the ".style" to "OSM2PGSQL_OPTIONS"

---

serving-tiles/manually-building-a-tile-server-debian-11.md

Historically, ModTileMissingRequestTimeout was set to 30.  The version packaged into Debian now has 10 (as well has offering more customisations).
I've updated manually-building-a-tile-server-debian-11.md to suggest increasing 10 to 30 as "target market" users of this guide will likely at least initially have a slower server that might need longer to render tiles.  
A lower number will make perfect sense to some people, but I think the default suggested in this guide should be higher.
Note that "the first time that people view tiles" they won't have pre-rendered anything, so will be waiting for their first tile at zoom <= 12 (something unlikely to happen in normal operation).

Debian: default mod_tile timeout

---

providers.md

Unfortunately they have shut down their developer program, and the links lead only to an explanatory page.

Remove Skobbler from the providers list

---

_layouts/docs.html
serving-tiles/updating-as-people-edit-osm2pgsql-replication.md
serving-tiles/updating-as-people-edit-osmosis.md

Renamed "osm2pgsql" to "osm2pgsql-replication" to leave room for
as yet unwritten "pyosmium" unstructions.
Link to https://github.com/SomeoneElseOSM/mod_tile/blob/switch2osm/update_tiles.sh
Link to https://github.com/SomeoneElseOSM/mod_tile/blob/switch2osm/expire_tiles.sh
These scripts now have error checking in and detect if they are already running.

updating-as-people-edit

---

serving-tiles/updating-as-people-edit-osm2pgsql-replication.md
serving-tiles/updating-as-people-edit-pyosmium.md

Clear either /var/cache/renderd/update_tiles.sh.running or /var/cache/renderd/pyosmium/call_pyosmium.running at renderd startup so that neither cron job incorrectly things it is still running.

Clear ".running" files at renderd startup

---

serving-tiles/updating-as-people-edit-osmosis.md
serving-tiles/updating-as-people-edit-pyosmium.md

Versions of /etc/munin/plugins/replication_delay documented for osmosis (based the existing one that ships with mod_tile) and pyosmium (new, calls pyosmium_replag.sh).
There's no version for osm2pgsql-replication yet because "osm2pgsql-replication status" needs to read the database (tricky from munin), or perhaps grep "Backlog" from a logfile.

Displaying replication_delay in munin

---

serving-tiles/index.md

300GB for the whole planet appears to be outdated, nowadays it is not even enough to import Europe.
Maybe the number should even be higher?

Update index.md to reflect current storage need

---

serving-tiles/updating-as-people-edit-osmosis.md

I removed "and you’re not worried about automatically marking updated tiles as “dirty” to force re-rendering" from the "osmosis" instructions.  At the time I wrote that I hadn't got osm2pgsql-replication to handle dirty tiles at all because I hadn't yet identified the problem as https://github.com/openstreetmap/mod_tile/issues/286 .  With the instructions in place elsewhere in the switch2osm documentation there's no need for this caveat.

remove "and you’re not worried about ..." warning

---

serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts.md

get-fonts.sh fails without it and it does not seem to be installed by default on Ubuntu 22.04.

Add curl to list of packages to install

---

using-tiles/index.md

Unexpectedly found that there was a link missing here when I read this article, "**WHERE IS THE LIST?**"

fix(using-tiles/index.md): add provider list link

---

_layouts/docs.html
serving-tiles/index.md
serving-tiles/manually-building-a-tile-server-debian-11.md
serving-tiles/manually-building-a-tile-server-debian-12.md

I've also tidied the menu and the "serving tiles" index so that only Debian 12, Ubuntu 22.04, Docker and Debian 11 remain on it.
I've changed the Debian 11 page to reflect that it has been released for ome time now.
I've fixed some minor typos elsewhere, including in pages no longer on the menu.
The changes for Debian 12 include:
* Changes for new versions of e.g. postgres.
* A workaround for the removal of a vanilla "etc/apache2/renderd.conf". See https://github.com/openstreetmap/mod_tile/issues/326
* Changes necessary to reflect other mod_tiles changes, including debugging turned off by default.
* Changes necessary to reflect Debian changes, such as no standard "/var/log/syslog".

Added Debian 12 page.

---

serving-tiles/manually-building-a-tile-server-debian-12.md

See: https://packages.debian.org/bookworm/node-carto
This allows to download a lot less packages from apt as we can skip installing npm, which has a LOT of dependencies. It is also cleaner to install all of the needed tools from Debian, and allows to skip an install step.
I tested it on a fresh Debian 12 install.
```console
$ apt list node-carto
Listing... Done
node-carto/stable,now 1.2.0-4 all [installed]
$ which carto
/usr/bin/carto
$ carto --version
1.2.0
```
I compared with the one installed from npm and it emits the same amount of warnings ([node-carto-warnings.log](https://github.com/switch2osm/switch2osm/files/12781810/node-carto-warnings.log)).
<details><summary>apt install node-carto</summary>
```console
$ sudo apt install node-carto
Reading package lists... Done
Building …
```

node-carto is back in Debian12 with a suitable version

---

serving-tiles/manually-building-a-tile-server-debian-12.md

Debian now seems to follow Ubuntu 22.04 in requiring explicit access to be given to directories below the working user's home.

Add note to allow access to stylesheet below user's home directory.

---

find-out-more.md
serving-tiles/manually-building-a-tile-server-16-04-2-lts.md
serving-tiles/manually-building-a-tile-server-18-04-lts.md
serving-tiles/manually-building-a-tile-server-20-04-lts.md
serving-tiles/manually-building-a-tile-server-debian-11.md
serving-tiles/manually-building-a-tile-server-debian-12.md
serving-tiles/manually-building-a-tile-server-ubuntu-21.md
serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts.md

switch2osm.github.io has moved to switch2osm.org; correct broken links

Fix githubio links

---

serving-tiles/manually-building-a-tile-server-debian-12.md

https://github.com/switch2osm/switch2osm/issues/271
Currently only the Debian 12 version done for now

Added a couple of lines to the Debian 12 notes to address #271

---

serving-tiles/manually-building-a-tile-server-debian-11.md
serving-tiles/manually-building-a-tile-server-debian-12.md
serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts.md
serving-tiles/manually-building-a-tile-server-ubuntu-24-04-lts.md

Minor formatting change to Debian 12.
No change to Docker; the upstream dockerfile targets 5.4.0.

Addressing #271 in the other 3 "latest versions".

---

serving-tiles/index.md

There is a redirect, but update the URL in the docs.

protomaps.com/extracts URL changed to slice.openstreetmap.us

---

providers.md

We were there at some point but not any longer for a reason I ignore. Let's reintegrate the list.

Add Oslandia to providers

---

serving-tiles/updating-as-people-edit-osm2pgsql-replication.md
serving-tiles/updating-as-people-edit-pyosmium.md

Issue raised (re nominatim) at https://community.openstreetmap.org/t/python-error-on-indexing-rank-on-full-planet-import-how-to-fix-it/130711/3 
The two osmium guides have been changed; two other typos also changed. 
The osmosis guide doesn't mention this flag and hasn't been changed.

Also use "osm2pgsql-replication is running" to control reimports

---

README.md

Notification of domain relocation
https://web.archive.org/web/20200309190114/http://openstreetmapdata.com/

openstreetmapdata.com -> osmdata.openstreetmap.de

---

docs/en/using-tiles/getting-started-with-maplibre.md

Fixing the problem of missing code of `build.ts` on the rendered "Getting started with MapLibre GL" page, plus misc style prettifying.

Fixed: build.ts code is not displayed in the "Getting Started with MapLibre GL".
