.travis.yml
Gemfile

CI improvements

---

README.md

Add basic design goals

---

_includes/leaflet.html
using-tiles/getting-started-with-leaflet.md
why-switch.md

Rework of the Leaflet example

---

README

You can see the error log on Travis-CI
https://travis-ci.org/switch2osm/switch2osm.github.io/builds/162764459
for illustrating.
My other PRs (#29 & #30  ) are failing due to this issue.

Fix README error when building on local machine

---

using-tiles/index.md

Like usual, looking for feedback to improve content. It adresses #27 and partially #4

Fix and improvements to using-tiles/index.md content

---

_config.yml
_includes/openlayers.html
using-tiles/getting-started-with-openlayers.md
using-tiles/index.md

I choose to make the sample iso functional with Leaflet. There is clearly more boiler plate and it's quite lengthy.
I'm looking for feedback.

Add OpenLayers tutorial

---

_config.yml

Move Case Studies under Why Switch?

---

_config.yml
serving-tiles/manually-building-a-tile-server-16-04-2-lts.md

Added 16.04 page from https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/ .
Also added it to the "serving tiles" menu.

Added "manually 16.04" page from wordpress site.

---

providers.md

Fix spellling of Camptocamp

---

serving-tiles/manually-building-a-tile-server-18-04-lts.md

In testing of a different style it was needed; add here is belt
and braces.

Added postgresql-10-postgis-scripts

---

other-uses.md

I don't know how to set the French sentence. and will provide a new PR when I will have found.

Add Gisgraphy as a Geocoding provider

---

providers.md

Previous link for AND gave a 404.  The page I've linked to seems to be mostly hosting, but does mention "please talk to us" as well.

Update providers.md - AND link gave 404

---

the-basics/index.md
why-switch.md

Remove references to Mapquest's open tiles, which aren't really a thing any more.

Remove mapquest

---

providers.md

Adding Jawg as a tile provider #94

Add Jawg as a tile provider

---

serving-tiles/building-a-tile-server-from-packages.md
serving-tiles/index.md
serving-tiles/manually-building-a-tile-server-16-04-2-lts.md
serving-tiles/manually-building-a-tile-server-18-04-lts.md
serving-tiles/using-a-docker-container.md

While browsing, I noticed some links were broken, so I tried to fix some, and updated some to HTTPS.

Updated some links

---

serving-tiles/manually-building-a-tile-server-18-04-lts.md

Ensure we're using "multiverse".
Work around some npm/mode changes in latest versions.
Fixes https://github.com/switch2osm/switch2osm.github.io/issues/117

Minor 18.04 changes:

---

providers.md

See https://www.esri.com/arcgis-blog/products/js-api-arcgis/mapping/new-osm-vector-basemap/

Add Esri as free OSM tile provider

---

providers.md

I run [Alantgeo](https://www.alantgeo.com.au) out of Australia where I offer consulting and development services related to OpenStreetMap

add Alantgeo to development services and consulting list

---

_layouts/docs.html
serving-tiles/index.md

It's been up for a week, minor typos have been corrected, so it now
makes sense to link it in with the rest.

Added links to new Debian 11 page.

---

serving-tiles/manually-building-a-tile-server-20-04-lts.md
serving-tiles/updating-as-people-edit.md

Designed to address https://github.com/switch2osm/switch2osm.github.io/issues/128#issuecomment-778814384

Make sudo clearer on the 20.04 page

---

_layouts/docs.html

Now that "Debian" is an option we need to clarify version numbers such as "20.04".

Update docs.html with "Ubuntu"

---

serving-tiles/manually-building-a-tile-server-20-04-lts.md

Just the indexes change needed for Ubuntu 20.04

Issue 150 fix for Ubuntu 20.04

---

_includes/leaflet.html

https://leafletjs.com/examples/quick-start/example.html

leaflet: update example to latest version 1.7.1

---

serving-tiles/manually-building-a-tile-server-ubuntu-21.md

Added new page serving-tiles/manually-building-a-tile-server-ubuntu-21.md .
Not yet linked into the indexes

Added serving-tiles/manually-building-a-tile-server-ubuntu-21.md

---

_layouts/docs.html
serving-tiles/index.md
serving-tiles/manually-building-a-tile-server-16-04-2-lts.md
serving-tiles/manually-building-a-tile-server-18-04-lts.md
serving-tiles/manually-building-a-tile-server-20-04-lts.md
serving-tiles/manually-building-a-tile-server-debian-11.md
serving-tiles/manually-building-a-tile-server-ubuntu-21.md
serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts.md
serving-tiles/manually-building-a-tile-server-ubuntu-22.md

Added Ubuntu 2204 page.  Also minor changes (git: to https:) on other pages.

Ubuntu 2204

---

serving-tiles/updating-as-people-edit.md

Added paragraph linking to
https://osm2pgsql.org/doc/manual.html#updating-an-existing-database
to
http://localhost:4000/serving-tiles/updating-as-people-edit/

"updating" page

---

serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts.md
serving-tiles/updating-as-people-edit.md

Minor updates to spelling in the prose - no changes to install steps.

minor typo fixes for serving-tiles

---

serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts.md

Added "how to turn debug on"
Removed reference to /var/lib/mod_tile in case render_expired is used later.

Ubuntu 22.04

---

_layouts/docs.html
serving-tiles/monitoring-using-munin.md

Most of the information here is from https://wiki.openstreetmap.org/wiki/User:SomeoneElse/Ubuntu_1804_tileserver_load#Munin , but updated for and tested on Ubuntu 22.04.

Added "munin" page.

---

_layouts/docs.html
serving-tiles/updating-as-people-edit-osm2pgsql-replication.md
serving-tiles/updating-as-people-edit-pyosmium.md

Added new "updating" page for PyOsmium; updated "osm2pgsql-replication" page to say that there is yet another option; added redirection on cron job on "osm2pgsql-replication" page.

Pyosmium 01

---

serving-tiles/manually-building-a-tile-server-18-04-lts.md
serving-tiles/manually-building-a-tile-server-20-04-lts.md
serving-tiles/manually-building-a-tile-server-debian-11.md
serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts.md

Change the text in the "fonts" section of current instructions to say "scripts/get-fonts.sh"

Get fonts.sh

---

_includes/leaflet.html
_includes/openlayers.html

Update tile.openstreetmap.org URLs

---

serving-tiles/updating-as-people-edit-osmosis.md

as per https://github.com/switch2osm/switch2osm/issues/203 and
https://github.com/openstreetmap/mod_tile/issues/292

Add caveat for osmosis tile expiry

---

case-studies.md

Resolves https://github.com/switch2osm/switch2osm/issues/96

Removed one of the case studies (dead link).

---

providers.md

+ Maptoolkit.com

---

serving-tiles/manually-building-a-tile-server-debian-12.md

(Timeout before giving up for a tile to be rendered)

Document increasing "ModTileRequestTimeout 3"

---

serving-tiles/manually-building-a-tile-server-ubuntu-24-04-lts.md

Just updating a minor text change

Merging contribution that someone accidentally made to the wrong place

---

find-out-more.md

Added missing links
Removed broken links
Updated some others (e.g. swapped help site for forum)

Various updates to "find out more" page.

---

other-uses.md

MapLibre link

---

serving-tiles/manually-building-a-tile-server-debian-11.md
serving-tiles/manually-building-a-tile-server-debian-12.md
serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts.md
serving-tiles/manually-building-a-tile-server-ubuntu-24-04-lts.md

See:
https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md#database-functions

Added instructions to load database functions

---

serving-tiles/manually-building-a-tile-server-ubuntu-24-04-lts.md

https://github.com/gravitystorm/openstreetmap-carto/issues/5013 
https://github.com/gravitystorm/openstreetmap-carto/pull/4893

Added a note about get-fonts still failing.  See issue / PR in description.

---

serving-tiles/manually-building-a-tile-server-debian-11.md
serving-tiles/manually-building-a-tile-server-debian-12.md
serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts.md
serving-tiles/manually-building-a-tile-server-ubuntu-24-04-lts.md

Unfortunately "get-external-data.py" is unhelpful when it fails, so I've added "if all else fails please ask in the forum".

Caveat more of the issues that can occur with get-external-data.py

---

serving-tiles/manually-building-a-tile-server-debian-12.md
serving-tiles/manually-building-a-tile-server-ubuntu-22-04-lts.md
serving-tiles/manually-building-a-tile-server-ubuntu-24-04-lts.md
serving-tiles/updating-as-people-edit-osm2pgsql-replication.md
serving-tiles/updating-as-people-edit-pyosmium.md

Rearrange instructions a little so they read more nicely.

Clarify instructions for updating config file
